#! /bin/sh

sxhkd &
polybar example &
compton --config .config/compton/compton.conf &

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width         	1
bspc config focused_border_color 	#ff0000
bspc config window_gap          	9

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle		true

bspc rule -a Emacs floating=off state=tiled
